version: '3.1'
services:
  postgresql:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./env/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local