
shell:
    # docker exec -it (-intraction mode) postgres(container name) 
	docker exec -it postgres psql -U root

createdb:
	docker exec -it postgres createdb --username=root --owner=root simple_bank