version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongodb'
    volumes:
      - myapp:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./mongo.env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: vinay
      ME_CONFIG_MONGODB_URL: mongodb://root:vinay@mongo:27017/
volumes:
  myapp:
    driver: local
    